### ISSUE TITLE
Disable S3 bucket versioning for cellxgene-data-public

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cell-census#241]
## Motivation

Due to having bucket versioning enabled on `s3://cellxgene-data-public`, deletion of temporary, weekly census builds will not result in S3 cost savings.

## Considerations

We may _not_ want to outright disable bucket versioning, since this bucket may be used for more than just cell-census data. An alternate solution would be have a script that properly deletes all the object versions.

## Definition of Done

- [ ] It is possible to _fully_ delete S3 objects for older cell census builds such that deleted data no longer incurs an AWS cost.
- [ ] Any previously delete-marked data object versions are permanently deleted (see #99)

## Tasks
One of:
- [ ] Update https://github.com/chanzuckerberg/single-cell-infra/blob/main/terraform/envs/prod/soma/main.tf#L24 to `false` and apply in TFE.
- [ ] Create a script or command to delete all versioned data objects for a specific cell census build.

And:
- [ ] Per https://docs.aws.amazon.com/AmazonS3/latest/userguide/DeletingObjectVersions.html, delete s3 object versions

**Comment by atolopko-czi** [comment]
I think we accomplish the goals of this issue #241 and issue #242 by:
1.  _keeping bucket versioning enabled_
2. adding an S3 lifecycle policy that deletes "non-current versions"

This assumes that _logically_ deleting a versioned object results in it having 1 non-current version (and 0 current versions), and that it would then be fully deleted by the lifecycle policy. Need to confirm this.

In this way, deleting non-LTS census builds will eventually be physically deleted and result in the desired cost savings. And if ever we accidentally delete a LTS census build, it can be easily recovered, if done so within the lifecycle policy's timeframe (e.g. 30 days). It also allows other non-census data that may be added to this bucket to remain versioned.

If we agree on this approach, we can replace #241 and #242 with this lifecycle-based design. @Bento007 @ebezzi @bkmartinjr Thoughts?

**Comment by bkmartinjr** [comment]
Can you clarify step 2 above -- I believe you imply a fixed delay between the delete and the actual garbage collection, i.e.,

> adding an S3 lifecycle policy that deletes "non-current versions" _after a 30 day delay_.

(in other words, there is a 30-day recovery period for any delete, regardless of release type - LTS or non-LTS)

If that is practicable, it sounds like a wonderful solution to me.

**Comment by atolopko-czi** [comment]
Superseded by #241
