### ISSUE TITLE
Add builder option to detect if build is necessary

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cell-census#247]
## Motivation

To avoid effort of performing the (currently) manual build process if there is no expected change to the census build.

## Considerations

The Discover API responses are currently insufficient to detect actual changes in datasets, since only canonical dataset IDs are returned and there are useful timestamps returned by the API methods that are currently called. Once https://github.com/chanzuckerberg/cell-census/issues/6 is implemented, this check will become much easier. As of now, H5ADs may need to be retrieved to detect actual data changes. Alternately, there may another Discover API method that returns a relevant timestamp that could be used (the currently called API methods do not provide any dataset timestamps).

Even if datasets have not changed, it is still necessary to perform a build if the builder itself (bug fixes, schema changes, etc.) has changed, so may also want to take into account the builder git sha1.

## Definition of Done

The builder can be invoked with an option that detects and reports whether a cell census build is necessary. 

## Tasks

- [ ] Add CLI options, '--skip-build-if-unchanged` (e.g.)
- [ ] Compare the `latest` build's dataset H5ADs to the current set of available H5ADs
- [ ] Compare the git SHA1 of `latest` build to the current builder's SHA1
- [ ] If both of the above comparisons match, report to user and exit early

**Comment by bkmartinjr** [comment]
Q: isn't it possible an H5AD is revised by curation since the last build?  How would that be detected?

**Comment by atolopko-czi** [comment]
> Q: isn't it possible an H5AD is revised by curation since the last build? How would that be detected?

Yes, attempted to address that in `Considerations` section.

**Comment by bkmartinjr** [comment]
> attempted to address that in Considerations section

I was under the impression that the asset ID changed upon each revision, even if the dataset ID did not.  If that is true, could that be retained in the build, and used as a flag to indicate change?

**Comment by brianraymor** [comment]
There is also the `revised_at` timestamp.

It would be helpful for @atolopko-czi to ensure that the new refinements to the Discover API related to surfacing collection/dataset versions addresses these requirements.

**Comment by brianraymor** [comment]
Per triage, closing. The focus will be on automating the build process in H2.
