### ISSUE TITLE
create top-level containerized script for full census build

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cell-census#265]
Create a docker image & script that encapsulates all steps of the regular full census build.  I.e., all steps in the manual build documentation:
- [x] verifies that the host meets requirements (memory, free disk, etc) [resolved by #272]
- [x] performs build with cell_census_builder package, with official default args [resolved by #272]
- [x] generate summary and summary diff from `latest` build  [resolved by #272]
- [x] ~copies build & build logs to S3~ (filed as #294)
- [x] ~performs release (add build to release.json) and update `latest` tag~ (filed as #295)
- [x] ~cleans up outdated releases (including removing from release.json)~ (filed as #296)
- [x] ~re-eval notebooks~
- [x] Additional: dockerize the above [resolved by #272]

These will almost certainly be a set of "steps" which can be invoked both separately and as a single flow.

NOTE: full automation depends on: #109

Related: #75 and #110.
