### ISSUE TITLE
schema change: dataset_presence

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cell-census#60]
The `dataset_presence` matrix needs to move to: `census_obj[“census_data”][organism].ms[“RNA”]["dataset_presence"]`

It is currently stored at `census_obj[“census_data”][organism].ms[“RNA”].varp[“dataset_presence”]`.

In addition to the move, the cell census builder should stop creating a `varp` collection in the Measurement, as it is no longer being used.

 Tracking list with owners:
- [x] *Pablo*: update cell census schema (#69)
- [x] *Andrew*: update the cell census builder/validator (#66)
- [x] *Bruce*: update the cell_census Python package and demo notebooks (#70)

**Comment by pablo-gar** [comment]
The schema has been changed in branch `pablo-gar/schema-update-presence-matrix` please note the new location and name of the object

**From**  `census_obj[“census_data”][organism].ms[“RNA”].varp[“dataset_presence_matrix”]` 
**To**  `census_obj[“census_data”][organism].ms[“RNA”][“feature_dataset_presence_matrix”]`

Please note the key is "feature_dataset_presence_matrix" the word feature was added to indicate this relates to features.

**Comment by pablo-gar** [comment]
One thing I did not add was in change in the schema version, in theory this is a major schema change but I don't know what the best way to proceed is for this stage in development is. I will defer to you @atolopko-czi and @bkmartinjr

**Comment by bkmartinjr** [comment]
Definitely change the schema version - it is a legit change and worth practicing how we want to use manage it.

**Comment by pablo-gar** [comment]
Done, schema is bumped to 1.0.0 since it breaks the cell census API

**Comment by bkmartinjr** [comment]
I don't recommend 1.0 - remember that with semver rules, prior to 1.0 you can bump it without regard to breakage.

I would simply make it 0.2 or whatever.

`1.0` signifies we are willing to start acting as if it is relatively stable, which it is *not*.

**Comment by pablo-gar** [comment]
Got it, thanks. I went with changing major since it was breaking the API, but I take it now that this refers to _other_ APIs

It is now 0.2.0

**Comment by bkmartinjr** [comment]
No, it refers to different rules pre-release...

**Comment by atolopko-czi** [comment]
OK to close?

**Comment by bkmartinjr** [comment]
yes, AFAIK.

@pablo-gar  ?

**Comment by pablo-gar** [comment]
Yes
